package eu.seitzal.insight

import java.io.PrintWriter
import java.io.IOException

class HtmlBuilder(content : () => String) {
  @throws(classOf[IOException])
  def export(path : String) : Unit = {
    val pw = new PrintWriter(path, "UTF-8")
    pw.write(content())
    pw.close()
  }
}

object HtmlBuilder {

  def fromDataFrame(data : DataFrame, 
      title : String = "Untitled dataset") = {
    def content() : String =
      "<!DOCTYPE html>\n" +
      "<html>\n" +
      "<head>\n" +
      "<title>" + title + "</title>\n" +
      "<style type=\"text/css\">\n" +
      "body {\n" +
      "  font-family: \"Helvetica Neue\", sans-serif;\n" +
      "}\n" +
      "table, tr, td, th {\n" +
      "  border: 1px solid black;\n" +
      "  border-collapse: collapse;\n" +
      "}\n" +
      "td {\n" +
      "  padding: 5px;\n" +
      "}\n" +
      "th {\n" +
      "  font-weight: normal;\n" +
      "  text-align: left;\n" +
      "  padding: 5px;\n" +
      "  color: #ffffff;\n" +
      "  background-color: #555555;\n" +
      "}\n" +
      "</style>\n" + 
      "</head>\n" +
      "<body>\n" +
      "<div align=\"center\"><h1>" + title + "</h1></div>\n" +
      "<table align=\"center\">\n<tbody>\n" +
      "<tr>\n" +
      data.getRows.head.map(
          cname =>
          "<th>" + cname + "</th>\n"
      ).mkString +
      "</tr>\n" +
      data.getRows.tail.map(
        row =>
        "<tr>\n" +
        row.map(
          item =>
          "<td>" + item + "</td>\n"
        ).mkString +
        "</tr>\n"
      ).mkString +
      "</tbody>\n</table>\n" +
      "<div align=\"center\"><i><br />Table generated by Insight version " +
      VERSION +
      ", " +
      Helper.timestamp +
      "</i></div>\n</body>\n</html>\n"
    new HtmlBuilder(content)
  }

  def fromContingencyTable(ct : ContingencyTable) = {
    def content() : String = 
      "<!DOCTYPE html>\n" +
      "<html>\n" +
      "<head>\n" +
      "<title>Contingency Table</title>\n" +
      "<style type=\"text/css\">\n" +
      "body {\n" +
      "  font-family: \"Helvetica Neue\", sans-serif;\n" +
      "}\n" +
      "table, tr, td, th {\n" +
      "  border: 1px solid black;\n" +
      "  border-collapse: collapse;\n" +
      "  vertical-align: top;\n" +
      "}\n" +
      "td {\n" +
      "  padding: 5px;\n" +
      "}\n" +
      ".frame {\n" +
      "  font-weight: normal;\n" +
      "  text-align: center;\n" +
      "  vertical-align: middle;\n" +
      "  padding: 5px;\n" +
      "  color: #ffffff;\n" +
      "  background-color: #555555;\n" +
      "}\n" +
      ".sum {\n" +
      "  background-color: #bbbbbb;\n" +
      "}\n" +
      "</style>\n" +
      "</head>\n" +
      "<body>\n" +
      "<table align=\"center\">\n<tbody>\n" +
      "<tr>\n" +
      "<th class=\"frame\"></th>\n" + {
      for(colLabel <- ct.colLabels)
        yield "<th class=\"frame\">" + colLabel + "</th>\n"
      }.mkString + 
      "<th class=\"frame\">Σ Row</th></tr>\n" + {
      for(row <- 0 until ct.rowLabels.length)
        yield "<tr>\n" +
          "<td class=\"frame\">" + ct.rowLabels(row) + "</td>\n" + {
          for (col <- 0 until ct.colLabels.length)
            yield "<td>\n" +
              ct.cells(row)(col).toString + "<br />\n" +
              Helper.roundTo(ct.relCells(row)(col), 6).toString + " T<br />\n" +
              Helper.roundTo(ct.rowProps(row)(col), 6).toString + " R<br />\n" +
              Helper.roundTo(ct.colProps(row)(col), 6).toString + " C\n" +
              "</td>\n"
          }.mkString +
          "<td class=\"sum\">\n" +
          ct.rowTotal(row).toString + "<br />\n" +
          ct.relRowTotal(row).toString + " T<br />\n" +
          "</td>\n" +
          "</tr>\n"
      }.mkString +
      "<tr>\n" +
      "<td class=\"frame\">Σ Col</td>\n" + {
        for (col <- 0 until ct.colLabels.length)
          yield "<td class=\"sum\">\n" +
            ct.colTotal(col).toString + "<br />\n" +
            ct.relColTotal(col).toString + " T\n" +
            "</td>\n"
      }.mkString +
      "<td class=\"sum\">" + ct.grandTotal + "</td>\n" +
      "</tr>\n" +
      "</tbody>\n</table>\n" +
      "<div align=\"center\"><i><br />Table generated by Insight version " +
      VERSION +
      ", " +
      Helper.timestamp +
      "</i></div>\n</body>\n</html>\n"
    new HtmlBuilder(content)
  }

}